### ISSUE TITLE
Recruit users to test and give feedback

### ISSUE THREAD

**Issue by sheesania** [sheesania/anoixo#28]

**Comment by nurkkala** [comment]
Who did you get?

**Comment by sheesania** [comment]
Dr. Heth, Dr. MaGee, and possibly Dr. Flanders. I'm also talking to Dr. Heth about working with some of his students (#36). Dr. Young is interested too but currently out of the country.

Closer to the end of J term, I'll try to make a list of the people who were involved for anyone who takes on the project after me (#45).
